TicketCare-Production/src/java/manageBean/ReceiverBean.java
package manageBean;

import entity.ReceiverFacade;
import entity.Receiver;
import entity.receiverDAO;
import javax.inject.Named;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.context.RequestContext;

/**
 * 票卷接受者
 *
 * @author hychen39@gmail.com
 */
@Named(value = "receiver")
@SessionScoped
public class ReceiverBean implements Serializable {

    static public final String FILENAME = "Receivers.txt";
    final static public String RECEIVER_ADD_PAGE = "individualData-add";
    final static public String RECEIVER_DATA_PAGE = "adminIndividual";
    final static public String RECEIVER_VIEWDETAIL_PAGE = "individualData-detail";

    enum FormMode {
        CREATE, EDIT
    }

    private int birthYear;
    private int birthMonth;
    private int birthDay;
    private receiverDAO receiverDAO;
    private List<Receiver> filteredReceiver;

    @EJB
    private ReceiverFacade receiverDataFacade;
    private Receiver currentReceiver;
    private FormMode formMode;

    public ReceiverFacade getReceiverDataFacade() {
        return receiverDataFacade;
    }

    public void setReceiverDataFacade(ReceiverFacade receiverDataFacade) {
        this.receiverDataFacade = receiverDataFacade;
    }

    public Receiver getCurrentReceiver() {
        return currentReceiver;
    }

    public void setCurrentReceiver(Receiver currentReceiver) {
        this.currentReceiver = currentReceiver;
    }

    public FormMode getFormMode() {
        return formMode;
    }

    public void setFormMode(FormMode formMode) {
        this.formMode = formMode;
    }

    public List<Receiver> getFilteredReceiver() {
        return filteredReceiver;
    }

    public void setFilteredReceiver(List<Receiver> filteredReceiver) {
        this.filteredReceiver = filteredReceiver;
    }

    /**
     * Creates a new instance of Receiver
     */
    public ReceiverBean() {
    }

    @PostConstruct
    public void initBean() {
        //defaul the birth date
        setBirthYear(2016);
        // Month index start from 0
        setBirthMonth(1);
        // Day index start from 1
        setBirthDay(1);
        // create a new Receiver entity instance
        currentReceiver = new Receiver();
        List<String> interistrings = new ArrayList<>();
        currentReceiver.setInterestings(interistrings);
        currentReceiver.setInterestings(new ArrayList<String>());
        // init ReceiverDAO
        receiverDAO = new receiverDAO();
        receiverDAO.setPath(FacesContext.getCurrentInstance().getExternalContext().getRealPath("/"));
        receiverDAO.setFilename(FILENAME);
    }

    public receiverDAO getReceiverDAO() {
        return receiverDAO;
    }

    public void setReceiverDAO(receiverDAO receiverDAO) {
        this.receiverDAO = receiverDAO;
    }

    public int getBirthYear() {
        return birthYear;
    }

    public void setBirthYear(int birthYear) {
        this.birthYear = birthYear;
    }

    public int getBirthMonth() {
        return birthMonth;
    }

    public void setBirthMonth(int birthMonth) {
        this.birthMonth = birthMonth;
    }

    public int getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(int birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * 儲存 {@link #receiverEntity} 到檔案中。
     */
    public void save() {
        // 你沒有此目標 facelets
//        String targetPage = "/manage/cases/listAllReceivers";
//        String targetPage = "/individual";
        // create the year, month, and day fields to date
        StringBuilder birthDateBuilder = new StringBuilder();
        birthDateBuilder.append(getBirthYear()).append("/");
        birthDateBuilder.append(getBirthMonth()).append("/");
        birthDateBuilder.append(getBirthDay());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date birthDate = Calendar.getInstance().getTime();
        try {
            birthDate = sdf.parse(birthDateBuilder.toString());
        } catch (ParseException ex) {
            Logger.getLogger(ReceiverBean.class.getName()).log(Level.SEVERE, null, ex);
            // Throw error Message
            FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage("Errors occur when make the birth date."));
        }
        //Set the birth date property for the Receiver entity.
        currentReceiver.setBirth(birthDate);
        // call ReceiverDAO instance to save to file
        receiverDAO.save(currentReceiver);
        prepareAnotherCreate();
//        return targetPage;
    }

    /**
     * 為輸入下一筆新資料作準備動作。 先顯示對話框，表示儲存完成。之後，建立一個新的 {@link Receiver} 實體，供新的資料輸入。
     */
    private void prepareAnotherCreate() {
        // 顯示 MessageBox 訊息，表示儲存成功
        RequestContext.getCurrentInstance().showMessageInDialog(new FacesMessage("建檔成功"));
        currentReceiver = new Receiver();
    }

    /**
     * Get all receivers.
     *
     * @return
     */
    public List<Receiver> getReceivers() {
        List<Receiver> allList = null;
        allList = receiverDAO.getAll();
        return allList;
    }

    public List<Receiver> getAllIndividualData() {
        return receiverDataFacade.findAll();
    }

    /**
     * 建立新的 {@code Receiver} 實體，用以記錄使用者輸入的新資料。 Create a new {@code Receiver}
     * instance and assign to {@link ReceiverBean#receiverEntity}.
     *
     * @return 跳轉到輸入個案資料的頁面
     */
    public String prepareCreate() {
        //String targetPage = "individual-add";
        //receiverEntity = new Receiver();
        setBirthYear(1980);
        setBirthMonth(1);
        setBirthDay(1);
        //return targetPage;
        currentReceiver = new Receiver();
        formMode = FormMode.CREATE;
        return RECEIVER_ADD_PAGE;
    }

    public String saveIndividual() {

        try {
            currentReceiver.setBirth(convertBirthYearMonthDay());
        } catch (ParseException ex) {
            Logger.getLogger(ReceiverBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (formMode == FormMode.CREATE) {
            receiverDataFacade.create(currentReceiver);
        } else {
            receiverDataFacade.edit(currentReceiver);
        }
        return RECEIVER_DATA_PAGE;
    }

    public String prepareEdit(Receiver receiver) {
        currentReceiver = receiver;
        formMode = FormMode.EDIT;
        return RECEIVER_ADD_PAGE;
    }

    public void removeindividualData() {
        receiverDataFacade.remove(currentReceiver);
        currentReceiver = null;
    }

    public void removeIndividualAction(Receiver receiver) {
        currentReceiver = receiver;
        RequestContext requestContext = RequestContext.getCurrentInstance();
        requestContext.execute("PF('deleteDialogVar').show();");
    }

    public String viewIndividualAction(Receiver receiver) {
        currentReceiver = receiver;
        return RECEIVER_VIEWDETAIL_PAGE;
    }

    public Date convertBirthYearMonthDay() throws ParseException {
        StringBuilder birthDateStrBuffer = new StringBuilder();
        birthDateStrBuffer.append(Integer.toString(getBirthYear())).append("/");
        birthDateStrBuffer.append(Integer.toString(getBirthMonth())).append("/");
        birthDateStrBuffer.append(Integer.toString(getBirthDay()));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

        return dateFormat.parse(birthDateStrBuffer.toString());
    }
}

TicketCare-Production/src/java/manageBean/TicketDataBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageBean;

import entity.Ticket;
import entity.TicketDataFacade;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import manageBean.TicketDataBean.FormMode;
import org.apache.commons.io.IOUtils;
import org.primefaces.context.RequestContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author steven
 */
@Named(value = "ticketDataBean")
@SessionScoped
public class TicketDataBean implements Serializable {

    final static public String TICKET_ADD_PAGE = "ticketData-add";
    final static public String TICKET_DATA_PAGE = "adminTicketData";
    final static public String TICKET_VIEWDETAIL_PAGE = "ticketData-detail";

    enum FormMode {
        CREATE, EDIT,
    }

    @EJB
    private TicketDataFacade ticketDataFacade;
    private Ticket currentTicketData;
    private FormMode formMode;
    static final transient private Logger ticketDataBeanLogger = Logger.getLogger("TicketDataBean");

    private UploadedFile photoFile;

    public FormMode getFormMode() {
        return formMode;
    }

    public void setFormMode(FormMode formMode) {
        this.formMode = formMode;
    }

    public static Date getCurrentDate() {
        Calendar cal = Calendar.getInstance();
        return cal.getTime();
    }

    public TicketDataFacade getTicketDataFacade() {
        return ticketDataFacade;
    }

    public void setTicketDataFacade(TicketDataFacade ticketDataFacade) {
        this.ticketDataFacade = ticketDataFacade;
    }

    public Ticket getCurrentTicketData() {
        return currentTicketData;
    }

    public void setCurrentTicketData(Ticket currentTicketData) {
        this.currentTicketData = currentTicketData;
    }

    public List<Ticket> getAllTickerData() {
        return ticketDataFacade.findAll();
    }

    /**
     * 請直接使用 {@link #getCurrentDate() }
     *
     * @deprecated 2017/3/23 by hychen39@gmail.com
     * @return
     */
    public Date prepareCreateDate() {
        Calendar cal = Calendar.getInstance();
        return cal.getTime();
    }

    /**
     * Save the {@link #currentTicketData} to database by calling the
     * {@link #ticketDataFacade}.
     */
    public String saveTicket() {
        if (formMode == FormMode.CREATE) {
            ticketDataFacade.create(currentTicketData);
        } else {
            currentTicketData.setCreate_date(getCurrentDate());
            ticketDataFacade.edit(currentTicketData);
        }
        return TICKET_DATA_PAGE;
    }

    public String prepareCreate() {
        currentTicketData = new Ticket();
        currentTicketData.setCreate_date(getCurrentDate());
        formMode = FormMode.CREATE;
        return TICKET_ADD_PAGE;
    }

    public String prepareEdit(Ticket ticket) {
        currentTicketData = ticket;
        formMode = FormMode.EDIT;
        return TICKET_ADD_PAGE;
    }

    public void removeTicketData() {
        ticketDataFacade.remove(currentTicketData);
        currentTicketData = null;
    }

    public void removeTicketDataAction(Ticket ticket) {
        currentTicketData = ticket;
        RequestContext requestContext = RequestContext.getCurrentInstance();
        requestContext.execute("PF('deleteDialogVar').show();");
    }

    public String viewTicketDataAction(Ticket ticket) {
        currentTicketData = ticket;
        return TICKET_VIEWDETAIL_PAGE;
    }

    /**
     * Prepare for posting operation. Call PrimeFace dialog
     * <code>addNewPostDialogVar</code> to show up.
     *
     * @param ticket Ticket to post.
     */
    public void preparePosting(Ticket ticket) {
        currentTicketData = ticket;

        RequestContext.getCurrentInstance().execute("PF('addNewPostDialogVar').show();");

    }

    public void prepareOffPosting(Ticket ticket) {
        currentTicketData = ticket;
        RequestContext.getCurrentInstance().execute("PF('delPostDialogVar').show();");
    }

    public boolean isOnShelf(Ticket ticket) {
        return ticket.getStatus().equals(Ticket.Status.ON_SHELF);
    }

    public boolean isOffShelf(Ticket ticket) {
        return ticket.getStatus().equals(Ticket.Status.OFF_SHELF);
    }

    /**
     * Get the uploaded photo and put it to current ticket instance.
     *
     * @param event
     */
    public void handleFileUpload(FileUploadEvent event) {
        photoFile = event.getFile();
        try {
            // convert from stream to byte array
            byte[] content = IOUtils.toByteArray(photoFile.getInputstream());
            currentTicketData.setPhoto(content);
        } catch (IOException ex) {
            Logger.getLogger(TicketDataBean.class.getName()).log(Level.SEVERE, "圖片上傳失敗", ex);
        }
    }

    /**
     * Return the ticket photo as the type of StreamedContent.
     *
     * @param ticket
     * @return
     */
    public StreamedContent getTicketPhoto(Ticket ticket) {
        if (ticket.getPhoto() != null) {
            String msg = "Ticket to get image: " + ticket.getName();
            ticketDataBeanLogger.info(msg);
            return new DefaultStreamedContent(new ByteArrayInputStream(ticket.getPhoto()), "image/jpg");
        } else {
            return new DefaultStreamedContent();
        }
    }

    /**
     * Return the ticket photo as the type of StreamedContent.
     *
     * @return
     */
    public StreamedContent getTicketPhoto() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        if (facesContext.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            // So, we're rendering the view. Return a stub StreamedContent so that it will generate right URL.
            // The StreamedContent objects are placed in the session scope with an encrypted key.
            // After the rendering phase, the key is appended to image url that points to JSF resource handler.
            return new DefaultStreamedContent();
        } else {
            // Second request made by custom PrimeFaces ResourceHandler
            // So, browser is requesting the image. 
            // Convert the photo with byte array type to StreamedContent type.
            String ticketID = facesContext.getExternalContext().getRequestParameterMap().get("ticketID");
            Ticket ticket = ticketDataFacade.find(Long.parseLong(ticketID));
            if (ticket.getPhoto() != null) {
                String msg = "Ticket to get image:" + ticket.getId().toString();
                ticketDataBeanLogger.info(msg);
                return new DefaultStreamedContent(new ByteArrayInputStream(ticket.getPhoto()), "image/jpg");
            } else {
                ticketDataBeanLogger.info(ticketID + " get null from database");
                return new DefaultStreamedContent();
            }
        }
    }
}

TicketCare-Production/web/adminIndex.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Ticket Care</title>      
    </h:head>
    <h:body>
        <ui:debug/>
        <ui:composition template="/template/adminTemplate.xhtml" >
            <ui:define name="content">
                <h:graphicImage class="img-responsive" style="display: block; margin: auto; width: 50%;" library="images" name="logo.png"/>
            </ui:define>
            <ui:define name="footer">
                Footer for the administrator.
            </ui:define>
        </ui:composition>
    </h:body>
</html>

TicketCare-Production/web/adminIndividual.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ps="http://java.sun.com/jsf/passthrough" >
    <h:head>

        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <!--請在 template 中使用 stylesheet. -->
        <!--PrimeFaces 中已有 FontAwesome 了, 無需再額外使用 FontAwesome 的 stylesheet-->
    </h:head>
    <h:body>
        <ui:debug/>
        <ui:composition template="/template/adminTemplate.xhtml" >
            <ui:define name="head">
                <title>建立個案資料</title>
            </ui:define>
            <ui:define name="content">
                <h:body>
                    <h:form>
                        <legend>個案資料</legend>

                        <h:dataTable styleClass="table table-striped table-hover" value="#{receiver.allIndividualData}" var="individual" 
                                     style="font-size:16px; font-family: Microsoft JhengHei;">
                            <p:column >
                                <f:facet name="header"> 編號 </f:facet>             
                                <h:outputText value="#{individual.id}"/>
                            </p:column>

                            <p:column>
                                <f:facet name="header" > 姓名 </f:facet>          
                                <h:outputText value="#{individual.name}"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header" > 身分證字號 </f:facet>          
                                <h:outputText value="#{individual.idNumber}"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header" > 出生年月日 </f:facet>
                                <h:outputText value="#{individual.birth}">
                                    <f:convertDateTime type="date" pattern="yyyy/MM/dd" timeZone="Asia/Taipei" />
                                </h:outputText>
                            </p:column>
                            <p:column >
                                <f:facet name="header" >檢視</f:facet>
                                <p:commandButton  action="#{receiver.viewIndividualAction(individual)}" title="詳細資訊" icon="fa fa-file-text" />
                            </p:column>
                            <p:column >
                                <f:facet name="header" >修改</f:facet>
                                <p:commandButton  action="#{receiver.prepareEdit(individual)}" title="修改" icon="fa fa-pencil" />
                            </p:column>
                            <p:column >
                                <f:facet name="header" >刪除</f:facet>
                                <p:commandButton  action="#{receiver.removeIndividualAction(individual)}" title="刪除" icon="fa fa-trash" />
                            </p:column>
                        </h:dataTable><br/><br/>
                        <div style="float:right;" >
                            <p:row>
                                <h:commandButton styleClass="btn btn-success" value="新增" action="#{receiver.prepareCreate()}" style="font-size:18px; font-family: Microsoft JhengHei;"/>
                            </p:row>
                        </div>
                    </h:form>

                    <p:dialog id="deleteDialog" header="刪除個案資料"  widgetVar="deleteDialogVar" modal="true" 
                             dynamic="true" closable="false" draggable="false" closeOnEscape="true" resizable="false"
                             minHeight="40">
                        <h:form>
                            <h:outputText value="確認是否刪除 #{receiver.currentReceiver.name} 個案資料 ? " /><br/><br/>                            
                            <h:commandButton styleClass="add-ind-button" value="取消" onclick="PF('deleteDialogVar').hide();" />
                            <h:commandButton styleClass="add-ind-button" value="確定刪除" action="#{receiver.removeindividualData}" />
                        </h:form>
                    </p:dialog>
                </h:body> 
            </ui:define>
        </ui:composition>
    </h:body>
</html>

TicketCare-Production/web/adminTicketData.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ps="http://java.sun.com/jsf/passthrough" >

    <h:head>
        <title>Ticket Care</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <!--請在 template 中使用 stylesheet. -->
        <!--PrimeFaces 中已有 FontAwesome 了, 無需再額外使用 FontAwesome 的 stylesheet-->
    </h:head>
    <h:body>
        <ui:debug/>
        <ui:composition template="/template/adminTemplate.xhtml" >
            <ui:define name="content">
                <h:form id="ticketListForm">
                    <legend>票券資料</legend>
                    <h:dataTable id="listTable" styleClass="table table-striped table-hover" value="#{ticketDataBean.allTickerData}" var="ticket" style="font-size:16px; font-family: Microsoft JhengHei;">
                        <p:column >
                            <f:facet name="header"> 類別 </f:facet>          
                            <h:outputText value="#{ticket.category.name}"/>
                        </p:column>

                        <p:column>
                            <f:facet name="header" > 名稱 </f:facet>          
                            <h:outputText value="#{ticket.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 使用期限 </f:facet>          
                            <h:outputText value="#{ticket.startDate}">
                                <f:convertDateTime timeZone="Asia/Taipei" type="date" pattern="yyyy-MM-dd" />
                            </h:outputText> ~
                            <h:outputText value="#{ticket.endDate}">
                                <f:convertDateTime timeZone="Asia/Taipei" type="date" pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 數量 </f:facet>
                            <h:outputText value="#{ticket.qty}" />
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 狀態 </f:facet>
                            <h:outputText value="#{ticket.status}">
                                <f:converter converterId="ticketStatusConverter" />
                            </h:outputText>
                            <h:outputText value=" - #{postBean.findByTicket(ticket).id}" />
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 檢視 </f:facet> 
                            <p:commandButton action="#{ticketDataBean.viewTicketDataAction(ticket)}" 
                                             title="檢視" icon="fa fa-file-text" >
                            </p:commandButton>
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 修改 </f:facet> 
                            <p:commandButton  action="#{ticketDataBean.prepareEdit(ticket)}" title="修改" icon="fa fa-pencil" />
                        </p:column>   
                        <p:column>
                            <f:facet name="header" > 刪除 </f:facet> 
                            <p:commandButton  action="#{ticketDataBean.removeTicketDataAction(ticket)}" title="刪除" icon="fa fa-trash" />
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 上架 </f:facet> 
                            <p:commandButton  action="#{ticketDataBean.preparePosting(ticket)}" update=":ticketListForm:addNewPostDialogID"
                                              title="上架" icon="fa fa-angle-double-up" />
                        </p:column>    
                        <p:column>
                            <f:facet name="header" > 下架 </f:facet> 
                            <p:commandButton  action="#{ticketDataBean.prepareOffPosting(ticket)}" update=":ticketListForm:delPostDialogID"
                                              title="下架" icon="fa fa-angle-double-down" />
                        </p:column>    
                    </h:dataTable><br/><br/>

                    <p:dialog id="deleteDialog" header="刪除票券資料" widgetVar="deleteDialogVar" modal="true" 
                             dynamic="true" closable="false" draggable="false" closeOnEscape="true" resizable="false"
                             minHeight="40">
                        <h:form>
                            <h:outputText value="確認是否刪除 #{ticketDataBean.currentTicketData.name} 票券資料 ? " /><br/><br/>
                            <h:commandButton styleClass="add-ind-button"  value="取消" onclick="PF('deleteDialogVar').hide();" />
                            <h:commandButton styleClass="add-ind-button"  value="確定刪除" action="#{ticketDataBean.removeTicketData}" />
                        </h:form>
                    </p:dialog>

                    <p:dialog id="addNewPostDialogID" 
                              header="上架票券" widgetVar="addNewPostDialogVar"  modal="true" 
                             dynamic="true" closable="false" draggable="false" closeOnEscape="true" resizable="false"
                             minHeight="40">

                        <h:outputText value="確認是否上架 #{ticketDataBean.currentTicketData.name} 票券？" /><br/>
                        <h:commandButton styleClass="add-ind-button" value="取消" 
                                         onclick="PF('addNewPostDialogVar').hide();"  />
                        <h:commandButton styleClass="add-ind-button" 
                                         onclick="PF('addNewPostDialogVar').hide();" 
                                         value="確定" action="#{postBean.addPostDB(ticketDataBean.currentTicketData)}">
                            <f:ajax execute="@form" render=":ticketListForm:listTable"  />
                        </h:commandButton>
                    </p:dialog>            
                    <p:dialog id="delPostDialogID" 
                              header="下架票券" widgetVar="delPostDialogVar"  modal="true" 
                             dynamic="true" closable="false" draggable="false" closeOnEscape="true" resizable="false"
                             minHeight="40">

                        <h:outputText value="確認是否下架 #{ticketDataBean.currentTicketData.name} 票券？" /><br/>
                        <h:commandButton styleClass="add-ind-button" value="取消" 
                                         onclick="PF('delPostDialogVar').hide();"  />
                        <h:commandButton styleClass="add-ind-button" 
                                         onclick="PF('delPostDialogVar').hide();" 
                                         value="確定" action="#{postBean.delPostDB(ticketDataBean.currentTicketData)}">
                            <f:ajax execute="@form" render=":ticketListForm:listTable"  />
                        </h:commandButton>
                    </p:dialog>
                    <div style="float:right;" >
                        <p:row>
                            <h:commandButton styleClass="btn btn-success" value="新增" action="#{ticketDataBean.prepareCreate()}" style="font-size:16px; font-family: Microsoft JhengHei;"/>
                        </p:row>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

TicketCare-Production/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Ticket Care</title>   
    </h:head>
    <h:body>
        <ui:debug/>
        <ui:composition template="/template/Template.xhtml" >
            <ui:define name="content">
                <ui:include src="/template/contents.xhtml" />
            </ui:define>
        </ui:composition>
    </h:body>
</html>