TicketCare-Production/src/java/entity/TicketDataFacade.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import com.tcare.jpa.utils.AbstractFacade;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.ejb.Stateless;
import javax.ejb.LocalBean;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;

/**
 * {@link AbstractFacade<T> 提供的方法說明請參考 {@link https://gist.github.com/hychen39/d370238f0ffac8c2c4ec71d950c3d501}
 *
 * @author steven
 */
@Stateless
@LocalBean
public class TicketDataFacade extends AbstractFacade<Ticket> {

    @PersistenceContext(name = "TicketCare-ProductionPU")
    private EntityManager em;

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }

    /**
     * 取得到現在為止仍有效期的票劵
     *
     * @return
     */
    public List<Ticket> getEffectiveTicket() {
        LocalDate localDate = null;
        List<Ticket> resultPosts = null;

        localDate = LocalDate.now();
        Date currentDate = java.sql.Date.valueOf(localDate);
        TypedQuery<Ticket> query = em.createNamedQuery("findEffectiveTicket", Ticket.class);
        query.setParameter("current_date", currentDate);
        resultPosts = query.getResultList();
        return resultPosts;
    }

    /**
     * 必要的預設建構子，初始化父類別
     */
    public TicketDataFacade() {
        super(Ticket.class);
    }
}

TicketCare-Production/web/admin/effectiveTicketReport.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ps="http://java.sun.com/jsf/passthrough" >

    <h:head>
        <title>媒合清單</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description" content="顯示媒合清單，並提供維護功能。" /> 
        <!--請在 template 中使用 stylesheet. -->
        <!--PrimeFaces 中已有 FontAwesome 了, 無需再額外使用 FontAwesome 的 stylesheet-->
    </h:head>
    <h:body>
        <ui:debug/>
        <ui:composition template="/template/adminTemplate.xhtml" >
            <ui:define name="content">
                <h:form>
                    <legend>媒合</legend>
                    <p:dataTable id="ticket_report"
                                 styleClass="table table-striped table-hover" 
                                 value="#{ticketDataBean.ticketDataFacade.effectiveTicket}" 
                                 var="ticket"
                                 selectionMode="single"
                                 selection="#{ticketDataBean.currentTicketData}"
                                 rowKey="#{ticket.id}">
                        <p:column >
                            <f:facet name="header"> 票券類別 </f:facet>          
                            <h:outputText value="#{ticket.category.name}"/>
                        </p:column>

                        <p:column>
                            <f:facet name="header" > 票券名稱 </f:facet>          
                            <h:outputText value="#{ticket.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 票券到期日 </f:facet>          
                            <h:outputText value="#{ticket.endDate}">
                                <f:convertDateTime timeZone="Asia/Taipei" type="date" pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header" > 剩餘張數 </f:facet>
                            <h:outputText value="#{ticket.onHandQty}"/>
                        </p:column>
                    </p:dataTable>
                    <br/><br/>
                    <div style="float:right;" >
                        <p:row>
                            <h:commandButton styleClass="btn btn-success" 
                                             value="媒合" 
                                             action="#{receiverCandidateBean.preparePage(ticketDataBean.currentTicketData)}">
                            </h:commandButton>
                        </p:row>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

TicketCare-Production/web/admin/receiverByCategoryReport.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ps="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>

    </h:head>
    <h:body>
        <ui:composition template="/template/adminTemplate.xhtml" >
            <ui:define name="head">
                <meta name="description" content="列出對某個類別有興趣的個案(Receiver)"/>
                <title>個案列表: 票劵編號: #{receiverCandidateBean.selectedTicket.id} 
                    類別編號:#{receiverCandidateBean.selectedTicket.category.id}</title>
            </ui:define>
            <ui:define name="content">
                <p:growl autoUpdate="true" />
                <h:form id="form">
                    <p:dataTable  id="candidateList"
                                  value="#{receiverCandidateBean.findReceiverByInterest(receiverCandidateBean.selectedTicket.category)}"
                                  var="r">
                        <f:facet name="header">
                            票劵編號: #{receiverCandidateBean.selectedTicket.id}
                            票券名稱:#{receiverCandidateBean.selectedTicket.name}<br/>
                            類別編號:#{receiverCandidateBean.selectedTicket.category.id}
                            類別名稱:#{receiverCandidateBean.selectedTicket.category.name}<br/>
                            票券到期日:<h:outputText value="#{receiverCandidateBean.selectedTicket.endDate}" >
                                <f:convertDateTime timeZone="Asia/Taipei" type="date" pattern="yyyy-MM-dd" />
                            </h:outputText><br/>
                            剩餘數量:#{receiverCandidateBean.selectedTicket.onHandQty}
                        </f:facet>
                        <p:column headerText="ID">
                            <h:outputText value="#{r.id}" />
                        </p:column>
                        <p:column headerText="Name">
                            <h:outputText value="#{r.name}" />
                        </p:column>
                        <p:column headerText="Phone">
                            <h:outputText value="#{r.area_code}" /> -
                            <h:outputText value="#{r.tel}" />
                        </p:column>
                        <p:column headerText="Interests">
                            <p:dataList value="#{r.interests}" var="interest" >
                                <h:outputText value="#{interest.name}" />
                            </p:dataList>
                        </p:column>
                        <p:column headerText="保留數量">
                            <h:outputText value="#{receiverCandidateBean.findReservQty(r.id, receiverCandidateBean.selectedTicket.id)}" />
                        </p:column>
                        <p:column>
                            <p:commandButton value="保留票券" 
                                             process="form"
                                             action="#{receiverCandidateBean.prepareReservTxn(r)}"
                                             update=":dlgForm:Dlg_resvTicket"
                                             oncomplete="PF('dlgResvTicket').show();"/>
                        </p:column>
                    </p:dataTable>
                </h:form>
                <!--Dialog-->
                <h:form id="dlgForm">
                    <!--Dialog -->
                    <p:dialog id="Dlg_resvTicket" header="保留票券" 
                              widgetVar="dlgResvTicket" 
                              modal="true" 
                              focus=":dlgForm:reserv_qty"
                              minHeight="200"
                              closeOnEscape="true">
                        <p:focus context="Dlg_resvTicket" />
                        <h:panelGrid columns="2">
                            <h:outputLabel value="票卷編號"/> 
                            <h:outputLabel 
                                value="#{receiverCandidateBean.ticketTxn.ticket_id}" />
                            <h:outputLabel value="交易時間"/> 
                            <h:outputLabel value="#{receiverCandidateBean.ticketTxn.txn_timestamp}" >
                                <f:convertDateTime timeZone="Asia/Taipei" type="date" pattern="yyyy/MM/dd" />
                            </h:outputLabel> 
                            <h:outputLabel value="個案編號"/> <h:outputLabel 
                                value="#{receiverCandidateBean.ticketTxn.receiver_id}" />
                            <h:outputLabel value="保留張數" for="reserv_qty"/> 
                            <p:inputText id="reserv_qty" required="true" 
                                         value="#{receiverCandidateBean.ticketTxn.reserv_qty}">
                            </p:inputText>
                            <h:outputLabel value="取票方式"/>
                            <h:selectOneMenu class="form-control"
                                             id="type" 
                                             value="#{receiverCandidateBean.ticketTxn.pickupMethod}" 
                                             converter="ticketPickupMethodConverter"
                                             required="true"
                                             requiredMessage="請選擇取票方式"
                                             >
                                <f:selectItem itemLabel="請選擇" itemValue="#{null}" noSelectionOption="true" />
                                <f:selectItems  
                                    value="#{volunteerTakeWayBean.allPickupMethod}" 
                                    var="takeway" itemLabel="#{takeway.way}"
                                    itemValue="#{takeway}"/>
                            </h:selectOneMenu>
                            <h:outputLabel value="取票期限"/> 
                            <p:calendar value="#{receiverCandidateBean.ticketTxn.dueDate}" />
                        </h:panelGrid>
                        <p:commandButton value="取消" onclick="PF('dlgResvTicket').hide()" />
                        <p:commandButton id="btnConfirm" 
                                         value="確認" 
                                         action="#{receiverCandidateBean.execReservTxn(receiverCandidateBean.ticketTxn)}" 
                                         update=":form:candidateList"
                                         oncomplete="PF('dlgResvTicket').hide();"/>
                        <p:defaultCommand target="btnConfirm" />
                    </p:dialog>
                </h:form>
                <h:form > <br/>
                    <div style="float:right;" >
                        <p:row> 
                            <h:commandButton styleClass="btn btn-success" value="前往派案區" action="ticketingRecords"/>
                            <h:commandButton styleClass="btn btn-primary" value="繼續媒合" action="effectiveTicketReport"/>
                          <!--  <h:commandButton styleClass="btn btn-success" value="返回主畫面" action="adminIndex"/> !-->
                        </p:row>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>